exports.help = require('./help.js')
exports.card = require('./card.js')
exports.hero = require('./hero.js')
exports.stats = require('./stats.js')
exports.skills = require('./skills.js')
// exports.login = require('./login.js')
// exports.logout = require('./logout.js')
// exports.deck = require('./deck.js')
